name: "Test Action"

on:
  push:
    branches:
      - "**"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - id: default
        uses: ./
      - name: Test current commit hash is used by default
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "${{ github.sha }}"
          actual: ${{ steps.default.outputs.long }}
